"""Rebuild the bundled display lookup from a pinned VoiceOver SQL snapshot.

Parses integer fields as data; never executes the downloaded SQL. Uses only the
Python standard library. Normal addon use requires neither Python nor a download.
"""
import argparse
from collections import Counter
import hashlib
import json
from pathlib import Path
import re
from urllib.request import urlopen

REVISION = "5cf7627fc5ba99d7c2545cf0c9f323eaef31ef09"
BASE = f"https://raw.githubusercontent.com/mrthinger/wow-voiceover/{REVISION}/"
FILES = {
    "CreatureDisplayInfo.sql": ("assets/sql/exported/CreatureDisplayInfo.sql", "c9d368cbfbf6b4231c055ee5bb2e6eb46057e27aa5f376e3c64d10d8ae879142"),
    "CreatureDisplayInfoExtra.sql": ("assets/sql/exported/CreatureDisplayInfoExtra.sql", "3ea2dd1d7006100fd375888a1bca497042aa23ec536e63255344b177b91912b5"),
    "LICENSE": ("LICENSE", "6b0382b16279f26ff69014300541967a356a666eb0b91b422f6862f6b7dad17e"),
}
RACES = {
    1: "Human", 2: "Orc", 3: "Dwarf", 4: "NightElf", 5: "Scourge",
    6: "Tauren", 7: "Gnome", 8: "Troll", 9: "Goblin", 10: "BloodElf",
    11: "Draenei", 12: "FelOrc", 13: "Naga", 14: "Broken", 15: "Skeleton",
    16: "Vrykul", 17: "Tuskarr", 18: "ForestTroll", 19: "Taunka",
    20: "NorthrendSkeleton", 21: "IceTroll",
}
ROOT = Path(__file__).resolve().parent.parent


def parse_rows(source, table, fields):
    """Read the leading numeric fields, validating their schema and row shape."""
    schema = re.search(rf"CREATE TABLE `{re.escape(table)}` \((.*?)PRIMARY KEY", source)
    if not schema:
        raise ValueError(f"Missing schema for {table}")
    columns = re.findall(r"`([^`]+)`", schema[1])
    if columns[:len(fields)] != list(fields):
        raise ValueError(f"Unexpected column order for {table}")
    prefix = f"INSERT INTO `{table}` VALUES "
    pattern = re.compile(r"\(" + r"\s*,\s*".join([r"(-?\d+)"] * len(fields)) + r"\s*,")
    rows = {}
    for line in source.splitlines():
        if not line.startswith("INSERT INTO "):
            continue
        if not line.startswith(prefix):
            raise ValueError(f"Unexpected insert in {table}")
        match = pattern.match(line[len(prefix):])
        if not match:
            raise ValueError(f"Invalid numeric row in {table}")
        values = tuple(map(int, match.groups()))
        if values[0] in rows:
            raise ValueError(f"Duplicate ID in {table}: {values[0]}")
        rows[values[0]] = values[1:]
    if not rows:
        raise ValueError(f"No rows in {table}")
    return rows


def join_rows(displays, extras):
    result = {}
    skipped = Counter()
    for display_id, (_, _, extra_id) in displays.items():
        if extra_id == 0:
            skipped["no_extra_record"] += 1
            continue
        identity = extras.get(extra_id)
        if identity is None:
            skipped["missing_extra_record"] += 1
            continue
        race, sex = identity
        if display_id <= 0 or race not in RACES or sex not in (0, 1):
            skipped["unsupported_identity"] += 1
            continue
        # Database sex is 0/1; UnitSex is 2/3. Keep this translation explicit.
        result[display_id] = race * 2 + sex
    return result, dict(sorted(skipped.items()))


def render(rows):
    lines = ["local _, NS = ...", "-- Generated by scripts/import-voiceover-races.py; do not edit.",
             f"-- Source: mrthinger/wow-voiceover @ {REVISION}",
             "-- Legacy display data; new/reassigned Forever displays may differ.",
             "-- Attribution/license: VOICEOVER-LICENSE.txt and docs/RACE_DATA.md.",
             "local identities = {"]
    for code in sorted(set(rows.values())):
        gender = "male" if code % 2 == 0 else "female"
        lines.append(f'    [{code}] = {{race="{RACES[code // 2]}", gender="{gender}"}},')
    lines += ["}", "local displays = {"]
    entries = [f"[{id}]={rows[id]}," for id in sorted(rows)]
    for i in range(0, len(entries), 8):
        lines.append("    " + " ".join(entries[i:i+8]))
    lines += ["}", f"NS.DisplayRaceCount = {len(rows)}",
              "function NS.DisplayIdentity(displayID)",
              "    return identities[displays[displayID]]", "end", ""]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", type=Path, help="Read the three pinned source files locally instead of downloading")
    parser.add_argument("--check", action="store_true", help="Verify committed output without writing")
    args = parser.parse_args()
    sources = {}
    for name, (path, expected) in FILES.items():
        if args.source_dir:
            data = (args.source_dir / name).read_bytes()
        else:
            with urlopen(BASE + path, timeout=30) as response:
                data = response.read()
        if hashlib.sha256(data).hexdigest() != expected:
            raise ValueError(f"SHA-256 mismatch for {name}; refusing to import")
        sources[name] = data.decode("utf-8")
    displays = parse_rows(sources["CreatureDisplayInfo.sql"], "db_CreatureDisplayInfo",
                          ("ID", "ModelID", "SoundID", "ExtendedDisplayInfoID"))
    extras = parse_rows(sources["CreatureDisplayInfoExtra.sql"], "db_CreatureDisplayInfoExtra",
                        ("ID", "DisplayRaceID", "DisplaySexID"))
    rows, skipped = join_rows(displays, extras)
    manifest = {
        "repository": "https://github.com/mrthinger/wow-voiceover", "revision": REVISION,
        "sources": {name: {"path": p, "sha256": h} for name, (p, h) in FILES.items()},
        "display_rows": len(displays), "extra_rows": len(extras), "mapped_displays": len(rows),
        "mapped_races": sorted({RACES[code // 2] for code in rows.values()}), "skipped": skipped,
    }
    output = {
        ROOT / "addon/ForeverDubbed/DisplayRaces.lua": render(rows),
        ROOT / "addon/ForeverDubbed/VOICEOVER-LICENSE.txt": sources["LICENSE"],
        ROOT / "data/voiceover-display-manifest.json": json.dumps(manifest, indent=2) + "\n",
    }
    for path, contents in output.items():
        if args.check:
            if path.read_text(encoding="utf-8") != contents:
                raise ValueError(f"Generated output differs: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(contents, encoding="utf-8", newline="\n")
    print(f"{'Verified' if args.check else 'Generated'} {len(rows)} display identities; skipped {skipped}")


if __name__ == "__main__":
    main()
